src/methodical/core.clj
src/methodical/impl/dispatcher/common.clj
src/methodical/util.clj
test/methodical/impl/dispatcher/common_test.clj
test/methodical/util_test.clj

Fixes #22 and #23. Also addresses an issue present in vanilla Clojure mulitmethods: https://clojure.atlassian.net/browse/CLJ-2234

prefers? should check ancestors; remove util/prefers?

---

project.clj
src/methodical/impl.clj
src/methodical/impl/cache/simple.clj
src/methodical/impl/combo/clojure.clj
src/methodical/impl/combo/clos.clj
src/methodical/impl/combo/operator.clj
src/methodical/impl/combo/threaded.clj
src/methodical/impl/method_table/clojure.clj
src/methodical/impl/method_table/standard.clj
test/methodical/impl/dispatcher/multi_default_test.clj

Currently, `methodical.interface` and `methodical.impl.standard` are marked as AOT. This leads to potemkin and its dependencies being compiled into the deployed JAR, which can cause opaque dependency issues in consuming projects. By explicitly `:require`ing `methodical.interface` before `import`ing any of the generated Java interfaces, AOT compiling these namespaces can be avoided.
Resolves #33. Resolves #40.
---
Notes for @camsaul:
- No tests or docs needed updating.
- I updated the configuration for `check-namespace-decls` because `methodical.interface` needs to be required for side effects.
---
Thanks for contributing to Methodical. Before open a pull request, please take a moment to:
lein test && lein lint
CircleCI will also run these same tests against your PR.
Markdown documentation …

Disable AOT so deps aren't compiled into JAR

---

project.clj
src/methodical/impl/dispatcher/common.clj
src/methodical/impl/dispatcher/everything.clj
src/methodical/impl/dispatcher/multi_default.clj
src/methodical/impl/dispatcher/standard.clj
src/methodical/impl/multifn/standard.clj
test/methodical/impl/dispatcher/common_test.clj
test/methodical/impl/multifn/cached_test.clj
test/methodical/impl/multifn/standard_test.clj
test/methodical/util_test.clj

The new `dominates?` method wasn't taking the default dispatch value into account, which caused other new 0.11.0 features like `effective-dispatch-value` and the new method reuse stuff the relied on it to work incorrectly. This actually resulted in a bug where the wrong methods would get used depending on what order things got cached.
The actual fix was fairly straightforward -- I implemented a new arity of `dispatcher.common/dominates?` that takes the default value in to account -- but most of this PR is tests I wrote while trying to root out the bug.

Fix bug with new dominates? method and related 11.0 features

---

project.clj
src/methodical/impl/multifn/standard.clj
test/methodical/impl/dispatcher/common_test.clj
test/methodical/impl/multifn/cached_test.clj
test/methodical/impl/multifn/standard_test.clj
test/methodical/util_test.clj

Fix a few more bugs with new 0.11.0 features.
-  `effective-dispatch-value` needs to combine dispatch composite dispatch values e.g. if we have a primary method `[Object ::parrot]` and an aux method `[String ::bird]` the effective dispatch value is `[String ::parrot]`.
- `effective-dispatch-value` needs to consider *all* aux methods, since they're all applicable

Fix a few more effective-dispatch-value bugs :wrench:

---

src/methodical/impl/dispatcher/multi_default.clj
src/methodical/impl/method_table/standard.clj
src/methodical/util.clj
test/methodical/impl/dispatcher/multi_default_test.clj
test/methodical/impl/method_table/standard_test.clj
test/methodical/util_test.clj

- `standard-method-table` now adds `^:dispatch-value` metadata to methods when they're added to the table. This is used in a few different places to determine the effective dispatch value and the like
- `effective-primary-method` now returns `^:dispatch-value` metadata 
- 
Fixes #61

Metadata should record ^:dispatch-value; have effective-primary-method return it

---

src/methodical/core.clj
src/methodical/util.clj
src/methodical/util/trace.clj
test/methodical/util/trace_test.clj
test/methodical/util_test.clj

Added new `u/dispatch-value` to use instead of calling `i/dispatch-value` (protocol method) directly. Protocols don't support varargs
Fixes #67

Fix trace, dispatch-fn etc with > 4 args

---

README.md
src/methodical/interface.clj

For eventual ClojureScript support. The interface is pretty stable at this point so the benefits of `definterface+` aren't as important. Also Potemkin `definterface+` ends up generating uncovered code which is affecting our Cloverage coverage numbers a bit.

Switch from p.types/definterface+ to defprotocol

---

src/methodical/util/trace.clj
test/methodical/util/trace_test.clj

- `trace` should use `pretty.core/pretty` to pretty-print `PrettyPrintable` things
- `trace` should use the same `description` method to print results as it uses to print args to method calls

Minor `trace` tweaks

---

src/methodical/impl/multifn/standard.clj
test/methodical/impl/multifn/standard_test.clj

Consider this case:
- A `:toucan` isa `:can`
- A `:toucan` isa `:bird`
- We have a preference for `:bird` over `:can`
- We have a primary method for `:can`
- We have a primary method for `:bird`
If you invoke the multimethod with dispatch value `:bird`, it will use the `:bird` primary method with no `next-method`.
If you invoke the multimethod with dispatch value `:toucan`, it will use the `:bird` primary method with the `:can` primary method as the `next-method`.
Thus even though dispatch values `:bird` and `:toucan` both use the `:bird` primary method, their _effective dispatch values_ are not the same; because invoking the method with dispatch value `:bird` and with dispatch value `:toucan` is not the same thing.
We need to consider all matching dispatch values when calculating …

Consider all primary methods when calculating effective dispatch value

---

.clj-kondo/config.edn
codecov.yml
dev/user.clj
resources/clj-kondo.exports/methodical/methodical/config.edn
resources/clj-kondo.exports/methodical/methodical/hooks/methodical/macros.clj
src/methodical/impl/cache/simple.clj
src/methodical/impl/cache/watching.clj
src/methodical/impl/combo/clojure.clj
src/methodical/impl/combo/clos.clj
src/methodical/impl/combo/operator.clj
src/methodical/impl/combo/threaded.clj
src/methodical/impl/dispatcher/everything.clj
src/methodical/impl/dispatcher/multi_default.clj
src/methodical/impl/dispatcher/standard.clj
src/methodical/impl/method_table/clojure.clj
src/methodical/impl/multifn/cached.clj
src/methodical/impl/multifn/standard.clj
src/methodical/impl/standard.clj
src/methodical/interface.clj
src/methodical/macros.clj
src/methodical/util.clj
src/methodical/util/trace.clj
test/methodical/impl/cache/watching_test.clj
test/methodical/impl/combo/clojure_test.clj
test/methodical/impl/dispatcher/multi_default_test.clj
test/methodical/impl/dispatcher/standard_test.clj
test/methodical/macros_test.clj

Resolves #36
Resolves #46
Resolves #109
Resolves #110
Resolves #113
I started by trying to add specs to `defmethod` and `defmulti` and realized leveraging those to parse args made way more sense than parsing things the hard way. While writing tests and improving the custom Kondo hook I realized we had a few ambiguous parses for `defmethod`. So this PR introduces the following new rules for dispatch values:
A dispatch value as parsed to `defmethod` (i.e., not-yet-evaluated) can be ANYTHING other than the following two
things:
1. an legal aux qualifier for the current method combination, e.g. `:after` or `:around`
It makes the parse for
```clj
(m/defmethod mf :after \"str\" [_])
```
ambiguous -- Is this an `:after` aux method with dispatch value `\"str\"`, or a primary method with dispatch …

Macro parsing overhaul

---

deps.edn
dev/user.clj
src/methodical/impl/cache/simple.clj
src/methodical/impl/cache/watching.clj
src/methodical/impl/combo/clojure.clj
src/methodical/impl/combo/clos.clj
src/methodical/impl/combo/operator.clj
src/methodical/impl/combo/threaded.clj
src/methodical/impl/dispatcher/everything.clj
src/methodical/impl/dispatcher/multi_default.clj
src/methodical/impl/dispatcher/standard.clj
src/methodical/impl/method_table/clojure.clj
src/methodical/impl/method_table/common.clj
src/methodical/impl/method_table/standard.clj
src/methodical/impl/multifn/cached.clj
src/methodical/impl/multifn/standard.clj
src/methodical/impl/standard.clj
src/methodical/util.clj
src/methodical/util/datafy.clj
test/methodical/datafy_test.clj
test/methodical/test_runner.clj

Datafying a multimethod will now give you a big dump of useful information like
```clj
{:ns           'methodical.datafy-test
:name         'methodical.datafy-test/mf
:arglists     '([x y])
:class        methodical.impl.standard.StandardMultiFn
:combo        {:class          methodical.impl.combo.threaded.ThreadingMethodCombination
:threading-type :thread-last}
:dispatcher   {:class         methodical.impl.dispatcher.multi_default.MultiDefaultDispatcher
:dispatch-fn   methodical.datafy-test/dispatch-first
:default-value :default
:hierarchy     #'clojure.core/global-hierarchy
:prefs         {:x #{:y}}}
:method-table {:class   methodical.impl.method_table.standard.StandardMethodTable
:primary {:default
{:ns       'methodical.datafy-test
:name …
```

Support datafying multifns

---

.clj-kondo/config.edn
src/methodical/core.clj
src/methodical/impl/cache/simple.clj
src/methodical/impl/cache/watching.clj
src/methodical/impl/combo/clojure.clj
src/methodical/impl/combo/clos.clj
src/methodical/impl/combo/operator.clj
src/methodical/impl/combo/threaded.clj
src/methodical/impl/dispatcher/everything.clj
src/methodical/impl/dispatcher/multi_default.clj
src/methodical/impl/dispatcher/standard.clj
src/methodical/impl/method_table/clojure.clj
src/methodical/impl/method_table/common.clj
src/methodical/impl/method_table/standard.clj
src/methodical/impl/multifn/cached.clj
src/methodical/impl/multifn/standard.clj
src/methodical/impl/standard.clj
src/methodical/interface.clj
src/methodical/macros.clj
src/methodical/util.clj
src/methodical/util/datafy.clj
src/methodical/util/describe.clj
src/methodical/util/trace.clj
test/methodical/datafy_test.clj
test/methodical/impl/combo/operator_test.clj
test/methodical/impl/dispatcher/multi_default_test.clj
test/methodical/impl/method_table/standard_test.clj
test/methodical/impl/multifn/standard_test.clj
test/methodical/macros_test.clj
test/methodical/util/describe_test.clj

Implement a describe tool

---

src/methodical/impl.clj
src/methodical/impl/dispatcher/standard.clj
src/methodical/macros.clj
test/methodical/clojure_test.clj
test/methodical/datafy_test.clj
test/methodical/impl/dispatcher/multi_default_test.clj
test/methodical/impl/dispatcher/standard_test.clj
test/methodical/macros_test.clj

Fixes #126
This also changes the error thrown on ambiguous methods from an `IllegalArgumentException` to a `clojure.lang.ExceptionInfo`, and the `ex-data` map now includes the namespace, file, and line where each of the conflicting methods is defined.

Ambiguous primary method errors include multimethod name

---

docs/dispatch-functions.md
src/methodical/core.clj
src/methodical/util/dispatch.clj
test/methodical/util/dispatch_test.clj

Resolves #16
Adds `dispatch-on-first-arg`, dispatch-on-first-two-args`, etc. for up to 4 args.

Add dispatch function util functions

---

src/methodical/impl/method_table/common.clj
src/methodical/impl/method_table/standard.clj
src/methodical/macros.clj
src/methodical/util.clj
test/methodical/impl/method_table/common_test.clj
test/methodical/macros_test.clj

Fixes #129
* Only **redefine** a multimethod if the non-metadata information has changed e.g. dispatch function or other options
* update the multimethod metadata whenever the `defmulti` form is re-evaluated to capture changes to docstring, `^:private` status, etc.

Overhaul the way `defmulti` triggers redefinition

---

src/methodical/impl/combo/operator.clj

Remove this warning
```
operator.clj:172 recur arg for primitive local: sum is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: sum
```

Fix warning in loop

---

README.md
src/methodical/interface.clj
test/methodical/util_test.clj

I updated the readme, and noticed some spelling mistakes while running the linter, so I fixed those too.
----
----
Thanks for contributing to Methodical. Before open a pull request, please take a moment to:
./scripts/lint-and-test.sh
GitHub Actions will also run these same tests against your PR.
Markdown documentation to different lines in a way that wouldn't change how the rendered page itself would
appear. These sorts of changes make a PR bigger than it needs to be, and, thus, harder to review.)
Of course, indentation and typo fixes are not covered by this rule and are always appreciated.
understand what's going on while we review it.
Once you've done all that, open a PR! Thanks for your contribution!

Add example for `:after :default` to the README

---

src/methodical/impl/combo/operator.clj

before:
```
❯ clj -M:"$ALIASES"
Warning: environ value /Users/dan/.sdkman/candidates/java/current for key :java-home has been overwritten with /Users/dan/.sdkman/candidates/java/21.0.2-tem
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.algo.generic.math-functions, being replaced by: #'clojure.algo.generic.math-functions/abs
operator.clj:172 recur arg for primitive local: sum is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: sum
2024-05-06 22:46:49,580 INFO metabase.util :: Maximum memory available to JVM: 8.0 GB
```
after:
```
❯ clj -M:"$ALIASES"
Warning: environ value /Users/dan/.sdkman/candidates/java/current for key :java-home has been overwritten with /Users/dan/.sdkman/candidates/java/21.0.2-tem
WARNING: abs already refers to: …
```

Fix some startup warnings about recur targets

---

src/methodical/impl/dispatcher/common.clj
src/methodical/impl/dispatcher/multi_default.clj

This PR makes small optimizations to the process of computing a primary method (namely, to `matching-primary-methods` function). The changes are mostly structural – replacing lazy transforms and expensive iteration with eager and optimized counterparts.
At first, I was under the impression that the time to construct a method for a dispatch value should not matter because of caching, but here and there in Metabase I find cases where the method is reconstructed – either because the method can't be cached, or in situations like https://github.com/camsaul/toucan2/pull/180. Hence, improving the efficiency of this otherwise cacheable process is still worth doing.

[dispatcher] Optimize primary method calculation

---

src/methodical/impl/multifn/standard.clj

Further improvements to method dispatching machinery. When it is cached, this shouldn't matter, but I keep encountering cases where it is not cached and thus it matters a bit.
For the benchmark, I've accumulated a sample of ~20k argument sets to `effective-dispatch-value` I got these results:
```
Before:
Time per call: 13.83 ms   Alloc per call: 31,446,785b
Time per call: 13.82 ms   Alloc per call: 31,446,785b
After:
Time per call: 7.44 ms   Alloc per call: 8,638,718b
Time per call: 7.40 ms   Alloc per call: 8,638,718b
```
Normalized to a single invocation, this means that a single invocation allocations dropped from `1.39KB` to `380B` which looks significant enough for something as basic as a multimethod invocation.

[multifn] Optimize non-cached effective-dispatch-value
